"""sua mensagem

Revision ID: 1872fe9478a3
Revises: 
Create Date: 2025-03-21 14:50:24.307218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1872fe9478a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('codigo', table_name='fornecedor')
    op.drop_index('email', table_name='fornecedor')
    op.drop_table('fornecedor')
    op.drop_table('composicao')
    op.drop_index('codigo_licenca', table_name='licencas')
    op.drop_index('ix_licencas_id', table_name='licencas')
    op.drop_table('licencas')
    op.drop_index('email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('balcao')
    op.drop_table('etapa_acompanhamento')
    op.drop_table('estoque')
    op.drop_table('produto')
    op.drop_table('categoria')
    op.drop_table('item_comanda')
    op.drop_index('ix_pagamentos_id', table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_table('setor')
    op.drop_table('item_comanda_acompanhamento')
    op.drop_table('etapa')
    op.drop_table('mesa')
    op.drop_index('ix_permissoes_usuario_id', table_name='permissoes_usuario')
    op.drop_table('permissoes_usuario')
    op.drop_table('forma_pagamento')
    op.drop_table('comanda')
    op.drop_index('cnpj_cpf', table_name='empresas')
    op.drop_index('email_contato', table_name='empresas')
    op.drop_index('email_personalizado', table_name='empresas')
    op.drop_index('nome', table_name='empresas')
    op.drop_table('empresas')
    op.drop_index('ix_balcoes_id', table_name='balcoes')
    op.drop_table('balcoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balcoes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='balcoes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_balcoes_id', 'balcoes', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj_cpf', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('email_contato', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email_personalizado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'ativo'"), nullable=False),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nome', 'empresas', ['nome'], unique=True)
    op.create_index('email_personalizado', 'empresas', ['email_personalizado'], unique=True)
    op.create_index('email_contato', 'empresas', ['email_contato'], unique=True)
    op.create_index('cnpj_cpf', 'empresas', ['cnpj_cpf'], unique=True)
    op.create_table('comanda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('numero_mesa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('senha', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('valor_total', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('pago', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balcao_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mesa_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['balcao_id'], ['balcao.id'], name='comanda_ibfk_2'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='comanda_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], name='comanda_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('forma_pagamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comanda_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metodo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('valor_pago', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', mysql.DATETIME(), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], name='forma_pagamento_ibfk_1'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='forma_pagamento_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permissoes_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tela', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('visualizar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('editar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('excluir', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('criar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='permissoes_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_permissoes_usuario_id', 'permissoes_usuario', ['id'], unique=False)
    op.create_table('mesa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codg', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('posicao', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='mesa_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('etapa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('posicao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='etapa_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='etapa_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('item_comanda_acompanhamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_comanda_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_adicional', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='item_comanda_acompanhamento_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_comanda_id'], ['item_comanda.id'], name='item_comanda_acompanhamento_ibfk_1'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='item_comanda_acompanhamento_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('setor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='setor_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pagamentos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor_pago', mysql.FLOAT(), nullable=False),
    sa.Column('data_pagamento', mysql.DATETIME(), nullable=True),
    sa.Column('licenca_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['licenca_id'], ['licencas.id'], name='pagamentos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pagamentos_id', 'pagamentos', ['id'], unique=False)
    op.create_table('item_comanda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comanda_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('acompanhamentos', mysql.TEXT(), nullable=True),
    sa.Column('status_producao', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pago', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], name='item_comanda_ibfk_1'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='item_comanda_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='item_comanda_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categoria',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='categoria_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('produto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('codigo_de_barra', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('disponibilidade', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id_und_med', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_fornecedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_setor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='produto_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], name='produto_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id'], name='produto_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_setor'], ['setor.id'], name='produto_ibfk_4', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estoque',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='estoque_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='estoque_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('etapa_acompanhamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_etapa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_produto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='etapa_acompanhamento_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_etapa'], ['etapa.id'], name='etapa_acompanhamento_ibfk_1'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], name='etapa_acompanhamento_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('balcao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codg', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('posicao', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='balcao_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('cargo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('criado_em', mysql.DATETIME(), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='usuarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('email', 'usuarios', ['email'], unique=True)
    op.create_table('licencas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('subpacotes', mysql.JSON(), nullable=True),
    sa.Column('valor', mysql.FLOAT(), nullable=False),
    sa.Column('data_ultimo_pagamento', mysql.DATETIME(), nullable=False),
    sa.Column('data_expiracao', mysql.DATETIME(), nullable=False),
    sa.Column('tolerancia', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo_licenca', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('dia_pagamento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='licencas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_licencas_id', 'licencas', ['id'], unique=False)
    op.create_index('codigo_licenca', 'licencas', ['codigo_licenca'], unique=True)
    op.create_table('composicao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('preco_adicional', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_produto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='composicao_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], name='composicao_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fornecedor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('empresa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='fornecedor_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'fornecedor', ['email'], unique=True)
    op.create_index('codigo', 'fornecedor', ['codigo'], unique=True)
    # ### end Alembic commands ###
