"""empty message

Revision ID: 150d43f4191c
Revises: f4c8702041b0
Create Date: 2025-01-25 09:47:15.203312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '150d43f4191c'
down_revision = 'f4c8702041b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_column('email2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email2', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
