"""empty message

Revision ID: 1d2b7f64aa72
Revises: 150d43f4191c
Create Date: 2025-01-26 21:15:53.574255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d2b7f64aa72'
down_revision = '150d43f4191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composicao_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composicao_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('preco_adicional', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id_composicao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_composicao'], ['composicao.id'], name='composicao_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
