"""empty message

Revision ID: af138eb64530
Revises: 
Create Date: 2025-01-25 09:43:57.261977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af138eb64530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_adicional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composicao_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('preco_adicional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_composicao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_composicao'], ['composicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapa_acompanhamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('id_und_med',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('id_und_med',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('etapa_acompanhamento', schema=None) as batch_op:
        batch_op.drop_column('preco')

    op.drop_table('composicao_item')
    op.drop_table('composicao')
    # ### end Alembic commands ###
