"""empty message

Revision ID: f4c8702041b0
Revises: af138eb64530
Create Date: 2025-01-25 09:47:00.770728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c8702041b0'
down_revision = 'af138eb64530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email2', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_column('email2')

    # ### end Alembic commands ###
